export enum Country {
  CHINA, INDIA, UNITED_STATES, INDONESIA, BRAZIL, BANGLADESH, RUSSIA, MEXICO, JAPAN, PHILIPPINES, EGYPT, VIETNAM,
  TURKEY, IRAN, GERMANY, UNITED_KINGDOM, FRANCE, ITALY, SOUTH_AFRICA, SOUTH_KOREA, COLOMBIA, SPAIN, ARGENTINA,
  SUDAN, UKRAINE, POLAND, CANADA, SAUDI_ARABIA, UZBEKISTAN, PERU, MALAYSIA, YEMEN, NEPAL, NORTH_KOREA, AUSTRALIA,
  NIGER, CHILE, KAZAKHSTAN, ECUADOR, NETHERLANDS, BELGIUM, CZECHIA, GREECE, PORTUGAL, SWEDEN, BELARUS, AUSTRIA,
  SERBIA, SWITZERLAND, BULGARIA, DENMARK, FINLAND, NORWAY, IRELAND, LATVIA,
}
